### ISSUE TITLE
Error while installing the repo

### ISSUE THREAD

**Issue by manshu** [ARCANESOFT/ARCANESOFT#1]
$ php artisan serve                                   
  [ErrorException]                              
  chdir(): No such file or directory (errno 2) 

this is the path in bootstrap/app.php

```php
$paths = array_map('realpath', [
    'base'      => __DIR__ . '/..',
    'public'    => __DIR__ . '/../www/',
]);
```

**Comment by arcanedev-maroc** [comment]
You can't run `php artisan serve` because i've removed the `server.php` file from the route.

Try to use homestead or a web server.

**Comment by arcanedev-maroc** [comment]
Never mind @manshu, i fixed the issue.

## Installation:

```php
$ composer create-project arcanesoft/arcanesoft arcanesoft --prefer-dist
$ npm install && bower install
$ gulp
```

Edit the `.env` file (database, admin credentials, ...), for more details, check the documentation : https://laravel.com/docs/5.2/configuration#environment-configuration

```php
php artisan foundation:publish
php artisan foundation:setup
```
