### ISSUE TITLE
Class 'App/Application' not found in bootstrap/app.php

### ISSUE THREAD

**Issue by ranjithmnair** [ARCANESOFT/ARCANESOFT#2]
When i try to run my program it says 'Class 'App/Application' not found in bootstrap/app.php'. Please help me!

**Comment by arcanedev-maroc** [comment]
Did you installed this project properly ?

The proper way to install it is by running this command:
```
composer create-project arcanesoft/arcanesoft project-name --prefer-dist
```

Try to run `composer dump-autoload` and see if it solves your issue.

**NOTE : This project is still in heavy development.**

**Comment by ranjithmnair** [comment]
No sir, I just wrote that application.php in my app folder and change the bootstrap/app.php , because i have already a project that i want to convert as you did!

**Comment by arcanedev-maroc** [comment]
So you need to create the [Application Class](https://github.com/ARCANESOFT/ARCANESOFT/blob/master/app/Application.php).

**Application.php** with a Capital **A** and don't forget the namespace.

**Comment by ranjithmnair** [comment]
Yes i do! Sorry if this is a silly question because i'm new to laravel, other than these two files is there is any file i have to change?

**Comment by arcanedev-maroc** [comment]
Yes, you need to rename the public folder (In my case, i've changed the `public` folder to `www`).

**Comment by ranjithmnair** [comment]
No luck!
